input: inputs/AnalysisResults.root
output_dir: outputs

bc_types: ["BC_B", "BC_L", "BC_LE"] #["BC_SL_FT0", "BC_NSL_FT0"] #["BC_B", "BC_L", "BC_LE", "BC_SL_FDD"]
detectors: ["FT0VTx", "FDD"] #["FT0VTx", "FDD"]

cross_sections:
  "2023":
    FDD: 49.63 # mb  (49.69+49.57)/2
    FT0VTx: 52.72 # mb  (52.76+52.68)/2
  "2024":
    FDD: 50.425 # mb  (50.61+50.24)/2
    FT0VTx: 53.035 # mb  (53.21+52.86)/2